name: Hash Node Blog post
on:
  schedule: # Run workflow automatically
    - cron: "0 * * * *" # Runs every hour, on the hour
  workflow_dispatch: # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Pull in dev.to posts
        uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://gokilp.hashnode.dev/"
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          readme_path: ./README.md
          max_post_count: 5
          disable_sort: false
          filter_comments: "stackoverflow/Comment by $author/,stackexchange/Comment by $author/"
          template: default
          date_format: "UTC:ddd mmm dd yyyy h:MM TT"
          user_agent: rss-parser
          accept_header: application/rss+xml
          commit_message: Updated with the latest blog posts
          committer_username: blog-post-bot
          committer_email: blog-post-bot@example.com
          output_only: false
          enable_keepalive: true
          retry_count: 0
          retry_wait_time: 1
          disable_html_encoding: false
          categories_template: default
          disable_item_validation: false
          skip_commit: false
